### ISSUE TITLE
Crash with malformed input

### ISSUE THREAD

**Issue by jasperla** [cktan/tomlc99#50]
Hello,

The following input file (as produced by AFL) causes a NULL pointer derefence in libtomlc99:

```toml
[0]
0.0=[]
+.
```

For example with tomlcat:

```
% ./toml_cat ~/fuzzing/sessions/tomlc99/crash.toml                                                                                                                          [*][master]
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1218247==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7efe0688e07b bp 0x7ffdcd28b3b0 sp 0x7ffdcd28ab40 T0)
==1218247==The signal is caused by a READ memory access.
==1218247==Hint: address points to the zero page.
    #0 0x7efe0688e07b in __interceptor_strcmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:442
    #1 0x5581a2f29478 in toml_table_in /home/kali/fuzzing/tomlc99/toml.c:1772
    #2 0x5581a2f2c2bf in parse_keyval /home/kali/fuzzing/tomlc99/toml.c:1066
    #3 0x5581a2f2d5ec in toml_parse /home/kali/fuzzing/tomlc99/toml.c:1378
    #4 0x5581a2f2f13d in toml_parse_file /home/kali/fuzzing/tomlc99/toml.c:1459
    #5 0x5581a2f24a63 in cat /home/kali/fuzzing/tomlc99/toml_cat.c:158
    #6 0x5581a2f24417 in main /home/kali/fuzzing/tomlc99/toml_cat.c:188
    #7 0x7efe06666d09 in __libc_start_main ../csu/libc-start.c:308
    #8 0x5581a2f24579 in _start (/home/kali/fuzzing/tomlc99/toml_cat+0x4579)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:442 in __interceptor_strcmp
==1218247==ABORTING
```

or without ASAN in GDB:

```
Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0x940 ('@\t')
RBX: 0x55555555f960 --> 0x55555555f980 --> 0x55555555f940 --> 0x30 ('0')
RCX: 0x0
RDX: 0x0
RSI: 0x55555555f940 --> 0x30 ('0')
RDI: 0x0
RBP: 0x0
RSP: 0x7fffffffe358 --> 0x5555555573e0 (<toml_table_in+64>:     test   eax,eax)
RIP: 0x7ffff7f3f00a (<__strcmp_avx2+26>:        vmovdqu ymm1,YMMWORD PTR [rdi])
R8 : 0x0
R9 : 0x7fffffffe190 --> 0x0
R10: 0xfffffffffffff287
R11: 0x7ffff7f3eff0 (<__strcmp_avx2>:   mov    eax,edi)
R12: 0x55555555f980 --> 0x55555555f940 --> 0x30 ('0')
R13: 0x55555555f968 --> 0x0
R14: 0x55555555e48b --> 0xa2e2b ('+.\n')
R15: 0x1
EFLAGS: 0x10287 (CARRY PARITY adjust zero SIGN trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff7f3effa <__strcmp_avx2+10>:   and    eax,0xfff
   0x7ffff7f3efff <__strcmp_avx2+15>:   cmp    eax,0xf80
   0x7ffff7f3f004 <__strcmp_avx2+20>:   jg     0x7ffff7f3f360 <__strcmp_avx2+880>
=> 0x7ffff7f3f00a <__strcmp_avx2+26>:   vmovdqu ymm1,YMMWORD PTR [rdi]
   0x7ffff7f3f00e <__strcmp_avx2+30>:   vpcmpeqb ymm0,ymm1,YMMWORD PTR [rsi]
   0x7ffff7f3f012 <__strcmp_avx2+34>:   vpminub ymm0,ymm0,ymm1
   0x7ffff7f3f016 <__strcmp_avx2+38>:   vpcmpeqb ymm0,ymm0,ymm7
   0x7ffff7f3f01a <__strcmp_avx2+42>:   vpmovmskb ecx,ymm0
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffe358 --> 0x5555555573e0 (<toml_table_in+64>:    test   eax,eax)
0008| 0x7fffffffe360 --> 0x7fffffffe430 --> 0x55555555e480 ("[0]\n0.0=[]\n+.\n")
0016| 0x7fffffffe368 --> 0x7fffffffe430 --> 0x55555555e480 ("[0]\n0.0=[]\n+.\n")
0024| 0x7fffffffe370 --> 0x7fffffffe430 --> 0x55555555e480 ("[0]\n0.0=[]\n+.\n")
0032| 0x7fffffffe378 --> 0x55555555f900 --> 0x55555555f8c0 --> 0x30 ('0')
0040| 0x7fffffffe380 --> 0x3
0048| 0x7fffffffe388 --> 0x555555558299 (<parse_keyval+217>:    mov    r8,QWORD PTR [rsp+0x8])
0056| 0x7fffffffe390 --> 0x55555555f8c0 --> 0x30 ('0')
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
__strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
```

This can be prevented by checking if `key == NULL` in `toml_table_in()` before attempting to dereference it.

**Comment by cktan** [comment]
Thanks!
